### ISSUE TITLE
DRY

### ISSUE THREAD

**Issue by Pivnoy** [Kaladin13/node_template#11]
https://github.com/Kaladin13/node_template/blob/25e46f08e47623b3d77a4a5523ecdb90066501fe/src/service/userService.ts#L30

Блок дублируется, можно было бы его вынести.

**Comment by Kaladin13** [comment]
надеюсь ты получишь это сообщение тут, крч я думаю нет особо смысла выносить этот логический блок, тк это всего 2 строчки и по логике приложения он ровно там где он должне быть - проверка удволетворяющих параметров перед дальнейшей обработкой запроса. следовательно он особо никуда больше не вписывается и просто возвращает один из статус кодов в логике обработки, думаю оставить его как есть будет правильным решением
